const STORE_KEY='rsrs-v1';
const uid=()=>crypto.randomUUID ? crypto.randomUUID() : String(Date.now())+Math.random().toString(36).slice(2);
const today=()=>new Date().toLocaleDateString('en-CA');
const copy=x=>JSON.parse(JSON.stringify(x));
const criterion=(title,expectation,section='Core review')=>({id:uid(),title,section,expectation,status:'unassessed',summary:'',assessment:'',comment:'',actions:'',studentResponse:'',location:'',remarks:''});
const caseSpecs=[
 ['Organisational / Practical Research Problem','Identify a consequential organisational problem, its setting, stakeholders and evidence of its practical importance.'],
 ['Problem Statement','Connect the practical problem, existing knowledge, unresolved issue and rationale for the proposed study.'],
 ['Research Questions and Objectives','State aligned, answerable questions and objectives that follow directly from the problem.'],
 ['Significance and Contribution','Explain expected value to practice and knowledge without promising results in advance.'],
 ['Scope of Study','Define the setting, population, phenomenon and deliberate exclusions with a reason for each boundary.'],
 ['Case and Unit of Analysis','Identify the bounded case and unit of analysis; distinguish the overall case from any embedded units.'],
 ['Case Boundaries','Specify temporal, organisational and geographic boundaries and explain their relevance.'],
 ['Literature Review','Synthesize relevant, credible scholarship around themes and unresolved debates rather than listing studies.'],
 ['Theoretical Foundation','Explain the chosen theoretical lens, its core ideas and its fit with the practical problem.'],
 ['Conceptual Framework','Show and explain the proposed concepts and relationships while remaining consistent with the case design.'],
 ['Case Study Research Design','Justify the case approach, selection logic and holistic or embedded design in relation to the questions.'],
 ['Sampling and Participants','Specify participants, selection criteria, recruitment and anticipated adequacy of evidence.'],
 ['Multiple Sources of Evidence','Identify complementary sources of evidence and how they will be triangulated.'],
 ['Data Analysis','Describe coding, within-case analysis, pattern development and an auditable path to findings.'],
 ['Trustworthiness / Research Rigour','Specify credible steps for transparency, reflexivity, corroboration and a clear chain of evidence.'],
 ['Framework Development','Explain how empirical findings and theory will inform the proposed practical framework.'],
 ['DBA-Level Contribution','Articulate the intended practice-facing and scholarly contribution at doctoral level.'],
 ['Overall Coherence','Ensure the problem, questions, theory, case design, evidence and analysis form a consistent study.']
];
const mkTemplate=(name,items)=>({id:uid(),name,criteria:items.map((item,i)=>criterion(item[0],item[1],i<7?'Research focus':i<10?'Knowledge base':i<15?'Research design':'Contribution & coherence'))});
const starterTemplates=()=>[
 mkTemplate('DBA Case Study — Proposal Review',caseSpecs),
 mkTemplate('DBA Quantitative — Proposal Review',[['Practical Research Problem','Establish a consequential managerial problem and its context.'],['Research Gap and Problem Statement','Connect the practical problem to an evidence-based gap.'],['Questions and Hypotheses','Align research questions, objectives and testable hypotheses.'],['Theoretical Model','Justify constructs and the directions of proposed relationships.'],['Research Design','Explain design, population and how the data answer the questions.'],['Sampling and Sample Size','Justify recruitment, adequacy and possible sampling bias.'],['Measures and Validity','Identify established measures and evidence for their suitability.'],['Analysis Plan','Match the analytical approach to each hypothesis and explain assumptions.'],['Ethics and Contribution','Address consent, confidentiality and expected practice and scholarly value.']]),
 mkTemplate('PhD — Proposal Review',[['Research Problem and Gap','Demonstrate a focused, defensible gap in knowledge.'],['Questions and Objectives','Align questions and objectives to the identified problem.'],['Critical Literature Review','Synthesize competing findings, concepts and theoretical positions.'],['Theoretical Contribution','Explain the potential originality and theoretical value.'],['Research Design','Justify methodology, epistemological position and design fit.'],['Sampling and Data','Describe sources, access, selection and adequacy.'],['Analysis and Rigour','Present a credible analytical and quality assurance strategy.'],['Ethics and Feasibility','Address ethical safeguards, resources and timeline.']]),
 mkTemplate('MBA Project Paper — Review',[['Business Problem','Describe the decision problem and why it matters to the organisation.'],['Objectives and Scope','Set practical, achievable objectives and boundaries.'],['Business Evidence','Use relevant internal and external evidence critically.'],['Method and Analysis','Explain how evidence is collected and analysed for the decision.'],['Recommendations','Propose actionable recommendations supported by findings.'],['Implementation and Limitations','Consider resources, risks, measures of success and limitations.']]),
 mkTemplate('General Research Review',[['Research Problem','State a clear, important and researchable problem.'],['Questions and Objectives','Ensure the questions and objectives follow from the problem.'],['Literature and Theory','Synthesize relevant evidence and explain the conceptual basis.'],['Methodology','Justify the design, participants, evidence and analysis.'],['Findings or Expected Contribution','Connect the findings or intended value to the questions.'],['Writing and Coherence','Present a logical, consistent and properly referenced argument.']])
];
const newReview=(template)=>({id:uid(),templateId:template.id,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),info:{institution:'',school:'',student:'',matric:'',programme:'',title:'',supervisor:'',coSupervisor:'',type:'Proposal review',stage:'Proposal',round:'Round 1',date:today()},criteria:copy(template.criteria).map(c=>({...c,id:uid()})),priorities:{p1:'',p2:'',p3:''},overall:'',overallStudentResponse:'',signature:''});
function demoReview(template){const r=newReview(template);Object.assign(r.info,{institution:'Example University',school:'School of Business',student:'Aisha Rahman (fictional)',matric:'DEMO-001',programme:'Doctor of Business Administration',title:'Governance of a Healthcare Clinic Licensing Network: A Case Study',supervisor:'Dr. Example Supervisor',type:'DBA case study proposal review',date:'2026-09-28'});
 const statuses=['yellow','yellow','green','yellow','green','yellow','yellow','yellow','yellow','red','yellow','yellow','green','yellow','yellow','yellow','yellow','yellow'];
 r.criteria.forEach((c,i)=>{c.status=statuses[i];c.summary=i===5?'The case and unit of analysis are appropriately identified, but the distinction between holistic and embedded single-case design requires clarification.':`${c.title} is addressed, but the proposal would benefit from ${i===9?'a clearer visual explanation and alignment with the case design':'more explicit justification and tighter alignment with the central research problem'}.`;c.assessment=i===5?'The study identifies the healthcare licensing network as the case and defines the licensing model as an organisational governance system as the unit of analysis.':`The draft proposal introduces ${c.title.toLowerCase()} in relation to a network of licensed primary-care clinics. It provides an initial account of the relevant organisational arrangements, but some connections remain implicit.`;c.comment=i===5?'The identification of the case and unit of analysis is a strength. However, the study should clarify whether individual clinics or stakeholder groups function as embedded units. This decision should remain consistent with the sampling and analytical strategy.':`The discussion offers a useful starting point. Make the rationale more explicit and explain how this element supports the research questions. Where claims concern clinic operations or governance, cite the supporting evidence and distinguish documented facts from proposed interpretations.`;c.actions=i===5?'1. Clarify whether the design is holistic or embedded.\n2. Identify embedded units if applicable.\n3. Provide a simple diagram of the case structure.\n4. Ensure consistency between case design, sampling, and analysis.':`1. State the decision or claim clearly in the relevant section.\n2. Add supporting sources or an example from the proposed setting.\n3. Check alignment with the problem, research questions and analysis plan.`;c.studentResponse='To be completed by student after revision.'});
 r.priorities={p1:'Clarify the case structure and revise the conceptual framework so that the unit of analysis, possible embedded units and evidence sources are consistent.',p2:'Strengthen the rationale for sampling, triangulation and analytical steps; trace each research question to suitable evidence.',p3:'Tighten terminology, remove repeated background material and check referencing throughout.'};r.overall='The proposal addresses a relevant governance challenge in primary healthcare and has a promising practical direction. The next draft should focus on coherence across the case definition, conceptual framework and method. The comments below identify specific revisions for the student to address before proceeding to data collection.';return r;}
